# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeName TBD
description: > # this means to ignore newlines until "baseurl:"
  Exploring the wide world of programming. One post at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ghotiphud.github.io/" # the base hostname & protocol for your site
twitter_username: ycason
github_username:  ghotiphud

# Global settings
timezone: America/New_York

# Build settings
#github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: "post"

gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-coffeescript
- jekyll-paginate

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME